---
- hosts: all
  tasks:
    - name: Include dynamic variables 
      import_playbook: ../static-assignments/common.yml 
      include: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: webservers
  tasks:
    - name: Webserver assignment
      import_playbook: ../static-assignments/webservers.yml